### ISSUE TITLE
Auto-Start or Start Hidden option for Linux client

### ISSUE THREAD

**Issue by TwisX** [klinker-apps/messenger-issues#684]
**Device with issue:** <HP Pavilion dv7 on Ubuntu 18.04>
**Primary device:** <Same as above>
**App version:** <2.0.0>

According to [this](https://github.com/klinker-apps/messenger-issues/issues/529#issuecomment-387173654), an auto-start option was added to the Windows client, but the API used does not support Linux.

Is there any chance that we will see this option on Linux at some point? Even an option or command line flag to start the program hidden would suffice, so that we could just add it to the startup programs list and not have the window pop up.

Thanks!

**Comment by klinker24** [comment]
You can already do this: https://github.com/klinker24/messenger-desktop/pull/1

Just add the `--no-gui` command line arg

**Comment by TwisX** [comment]
@klinker24 Unfortunately, that does not appear to work on the Linux client. It simply opens like the client window like normal. I've attached the command line output below:

`~$ pulse-sms --no-gui
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/Pulse SMS/resources/app-update.yml'
    at /opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/Pulse SMS/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at App.createWindow (/opt/Pulse SMS/resources/app.asar/main.js:109:15)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
There was a problem updating the app.
{ Error: ENOENT: no such file or directory, open '/opt/Pulse SMS/resources/app-update.yml'
    at /opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:370:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:395:11)
    at Lazy.AppUpdater.configOnDisk.Lazy (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:132:43)
    at Lazy.get value [as value] (/opt/Pulse SMS/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:281:46
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at AppImageUpdater.checkForUpdates (/opt/Pulse SMS/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at App.createWindow (/opt/Pulse SMS/resources/app.asar/main.js:109:15)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)
  cause: 
   { Error: ENOENT: no such file or directory, open '/opt/Pulse SMS/resources/app-update.yml'
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/opt/Pulse SMS/resources/app-update.yml' },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/opt/Pulse SMS/resources/app-update.yml' }
websocket: opened connection
`

**Comment by klinker24** [comment]
Do you see anything wrong with the code around it? It appears to be working perfectly fine for the user that implemented it. I can also confirm that it is working with the dev version of the app. The logic looks sound to me, but i don't know how it works with a production version like that, I suppose.

**Comment by klinker24** [comment]
You said you were on v2.0.0 of the desktop app. You need to update to the latest version to get this implementation. 2.3.0 is the latest.

**Comment by TwisX** [comment]
Ah, that was the issue. Works fine now, thanks!
